### ISSUE TITLE
Doesn't work after javascript/node file saved

### ISSUE THREAD

**Issue by uloco** [Rpinski/vscode-shebang-snippets#2]
Just writing `shebang` does nothing at the moment, if the file is already saved and has the extension `.js` or `.node`.

**Comment by Rpinski** [comment]
I can't reproduce that, when I start typing "shebang" in an empty `.js` file, VSCode already suggests the `shebang-node` snippet:

![js_shebangsnippet](https://user-images.githubusercontent.com/1767539/31865808-113720ae-b775-11e7-9267-e9c722ef4ac2.png)

I test here with latest stable VSCode 1.17.2 and Shebang Snippets 0.1.

**Comment by Rpinski** [comment]
Since the extension rework with 1.0.0, support for "shebang" has been removed in favor of "#". Therefore I'll close this issue.
