### ISSUE TITLE
Add support for Powershell Core

### ISSUE THREAD

**Issue by nawordar** [Rpinski/vscode-shebang-snippets#5]
I have recently started using PowerShell Core on Linux and it supports shebangs without problem.
The shebang for PSC is `#!/usr/bin/env powershell`. 

I can try to make an implementation if I have time. Thank you for this great plugin!

**Comment by Rpinski** [comment]
It looks like `#!/usr/bin/env pwsh` is the correct shebang for PowerShell Core, at least according to documentation. I will add it as new snippet!

**Comment by Rpinski** [comment]
Just released new version 0.1.4, where the snippet has been added.
