### ISSUE TITLE
Inserting shebang does not work

### ISSUE THREAD

**Issue by muuvmuuv** [Rpinski/vscode-shebang-snippets#6]
As you can see, it doesn't show any snippets. I have the latest VS Code (1.41.x) installed.

![Bildschirmvideo aufnehmen 2020-01-14 um 10 47 01](https://user-images.githubusercontent.com/11534760/72333140-9f712c80-36bb-11ea-9b70-032f67b7a6c1.gif)

**Comment by noraj** [comment]
Because the readme is outdated. See #7
