### ISSUE TITLE
Non ENV shebangs

### ISSUE THREAD

**Issue by Justxd22** [Rpinski/vscode-shebang-snippets#74]
Awesome extension well done ! 

can we get non env shebangs ? (a requirement for some workspaces)
like: 
`#!/usr/bin/node`
`#!/usr/bin/python`

**Comment by Rpinski** [comment]
Many thanks, @Justxd22!

Sure, I'll test non-env shebangs for the next big release I'm planning!

**Comment by Justxd22** [comment]
good work :D
